{% set name = "sirepo-bluesky" %}
{% set version = "0.4.1" %}
{% set sha256 = "fd083f3e4bf0851d3aa00a17e9c4c4c97b63d4f85708c50c60edeade52eecbf2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - inflection
    - ipython
    - matplotlib-base
    - numconv
    - numpy
    - ophyd
    - pymongo
    - pyqt >=5.9
    - requests
    - scikit-image
    - shadow3
    - srwpy
    - unyt

test:
  imports:
    - sirepo_bluesky

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
