{% set name = "sirepo-bluesky" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f717388de9191cf97e86c6def24062795c0d7fc13859cdf4a6f7ed78d289906d

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - area-detector-handlers
    - bluesky
    - databroker
    - inflection
    - ipython
    - matplotlib-base
    - numconv
    - numpy
    - ophyd
    - peakutils
    - pymongo
    - pyqt >=5.9
    - requests
    - shadow3 >=23.1.4
    - srwpy >=4.0.0b1
    - tfs-pandas
    - unyt
    - xraylib
    - zict <3.0.0

test:
  requires:
    - pip
  commands:
    - pip check || echo "No problem"
  imports:
    - sirepo_bluesky
    - sirepo_bluesky.madx_flyer
    - sirepo_bluesky.madx_handler
    - sirepo_bluesky.shadow_detector
    - sirepo_bluesky.shadow_handler
    - sirepo_bluesky.sirepo_bluesky
    - sirepo_bluesky.sirepo_flyer
    - sirepo_bluesky.sirepo_ophyd
    - sirepo_bluesky.srw_detector
    - sirepo_bluesky.srw_handler

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
