{% set name = "sirepo-bluesky" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a3fcb0f2dddc9fc4c2738a4612d3f5ff46522afdddb62a9213eee0cf85a858e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - area-detector-handlers
    - bluesky
    - databroker
    - inflection
    - ipython
    - matplotlib-base
    - numconv
    - numpy
    - ophyd
    - peakutils
    - pymongo
    - pyqt >=5.9
    - requests
    - shadow3
    - srwpy
    - tfs-pandas
    - unyt

test:
  imports:
    - sirepo_bluesky

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
