{% set name = "sirepo-bluesky" %}
{% set version = "0.5.0" %}
{% set sha256 = "047502b94ec7c17ead717ea15fd1ed642ca4caa777eb6089263908eb1d6cb96f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky
    - databroker <2.0.0b
    - inflection
    - ipython
    - matplotlib-base
    - numconv
    - numpy
    - ophyd
    - pymongo
    - pyqt >=5.9
    - requests
    - scikit-image
    - shadow3
    - srwpy
    - tfs-pandas
    - unyt

test:
  imports:
    - sirepo_bluesky

about:
  home: https://github.com/NSLS-II/sirepo-bluesky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sirepo-Bluesky interface

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
